# Generated by Django 2.2.13 on 2021-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210518_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_member',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('absent', 'Absent')], max_length=200, null=True),
        ),
    ]
