# Generated by Django 2.2.13 on 2021-05-21 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210519_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_member',
            name='participant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Participant'),
        ),
        migrations.AlterField(
            model_name='event_member',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Absent', 'Absent')], max_length=200, null=True),
        ),
    ]
