# Generated by Django 2.2.13 on 2021-05-21 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210521_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_member',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Event'),
        ),
    ]
