# Generated by Django 2.2.13 on 2021-05-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210521_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='number_of_participants',
        ),
    ]
